version: 1
services:
  - type: web
    name: hsa-games
    env: node
    plan: free
    buildCommand: yarn global add nuxt && yarn install && yarn build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      NODE_ENV: production
      API_URL: https://hsa-games.com
    nodeVersion: 18.x
