// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/10/2024, 10:39:57
const configMerger = require("C:/Users/Ale/Desktop/HSA/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/Ale/Desktop/HSA/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","C:/Users/Ale/Desktop/HSA/layouts/**/*.{vue,js,mjs}","C:/Users/Ale/Desktop/HSA/pages/**/*.{vue,js,mjs}","C:/Users/Ale/Desktop/HSA/composables/**/*.{js,ts,mjs}","C:/Users/Ale/Desktop/HSA/utils/**/*.{js,ts,mjs}","C:/Users/Ale/Desktop/HSA/{A,a}pp.{vue,js,mjs}","C:/Users/Ale/Desktop/HSA/{E,e}rror.{vue,js,mjs}","C:/Users/Ale/Desktop/HSA/app.config.{js,ts,mjs}"] } }));

module.exports = config
